export const InfoWorks = [
    '/works/parasoles/Acrilico Angus burger2.png',
    '/works/parasoles/Acrilico Encanto.png',
    '/works/parasoles/Avis Acrilico las plamas.png',
    '/works/parasoles/Aviso Acrilico (Delig2).png',
    '/works/parasoles/Aviso Acrilico Cangreburguer.png',
    '/works/parasoles/Aviso Acrilico con estructura.png',
    '/works/parasoles/Aviso Acrilico decoracion oficina.png',
    '/works/parasoles/Aviso Acrilico Decoracion oficina2.png',
    '/works/parasoles/Aviso Acrilico Lola2.png',
    '/works/parasoles/Aviso Acrilico Melon.png',
    '/works/parasoles/Aviso Acrilico Mi tierra alas.png',
    '/works/parasoles/Aviso Acrilico mi tierra alas2.png',
    '/works/parasoles/Aviso Acrilico Misofa.png',
    '/works/parasoles/Aviso Acrilico misofa2.png',
    '/works/parasoles/Aviso Acrilico Montecarlos.png',
    '/works/parasoles/Aviso Acrilico Montecarlos2.png',
    '/works/parasoles/Aviso Acrilico SAMGUNG.png',
    '/works/parasoles/Aviso AcrilicoCangreburguer2.png',
    '/works/parasoles/Aviso Acrlico Angus Burger.png',
    '/works/parasoles/Aviso Acrlico Cajas de luz.png',
    '/works/parasoles/Aviso acrlico entrada Lounge BAR.png',
    '/works/parasoles/Aviso Acrlico Huawei.png',
    '/works/parasoles/Aviso Acrlico lola.png',
    '/works/parasoles/Aviso acrlico pasaje la 17.png',
    '/works/parasoles/Aviso Auteco Acrilico.png',
    '/works/parasoles/Aviso Delig.png',
    '/works/parasoles/Aviso en acrilico base pared  lougth bar.png',
    '/works/parasoles/aviso en acrilico colombina.png',
    '/works/parasoles/Aviso en acrilico Dr alejandro2.png',
    '/works/parasoles/Aviso en acrilico Metal Motos.png',
    '/works/parasoles/Aviso En acrilico Oh lala.png',
    '/works/parasoles/AViso en acrilico Xiaomi.png',
    '/works/parasoles/Aviso en acrlico Dr alejandro.png',
    '/works/parasoles/Tatto aviso.png',
    '/works/parasoles/Tatto aviso 2.png',
    '/works/parasoles/Neon Aviso.png',
    '/works/parasoles/Letras metalicas.png',
    '/works/parasoles/letras metalicas parte3.png',
    '/works/parasoles/Letras metalicas con luz.png',
    '/works/parasoles/AVISO POPSY2.png',
    '/works/parasoles/AVISO POPSY.png',
    '/works/parasoles/Aviso Neon2.png',
    '/works/parasoles/Aviso Morata en acrilico.png'
];
